# Generated by Django 2.2.6 on 2019-10-14 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_sample', '0002_core_sample_control_sum'),
    ]

    operations = [
        migrations.AddField(
            model_name='core_sample',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания'),
        ),
    ]
