# Generated by Django 2.2.6 on 2019-10-13 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_sample', '0002_auto_20191013_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='core_sample',
            name='deposit',
            field=models.PositiveIntegerField(verbose_name='Месторождение'),
        ),
        migrations.AlterField(
            model_name='core_sample',
            name='hole',
            field=models.PositiveIntegerField(verbose_name='Скважина'),
        ),
    ]
