# Generated by Django 2.2.6 on 2019-10-13 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_sample', '0003_auto_20191013_1823'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='core_sample',
            options={'verbose_name': 'Керн', 'verbose_name_plural': 'Керны'},
        ),
        migrations.CreateModel(
            name='Fragment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dl_src', models.FilePathField(verbose_name='ДС изображение')),
                ('uv_src', models.FilePathField(verbose_name='УФ изображение')),
                ('top', models.FloatField(verbose_name='Вверх')),
                ('bottom', models.FloatField(verbose_name='Низ')),
                ('cs_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_sample.Core_sample', verbose_name='Керн')),
            ],
            options={
                'verbose_name': 'Фрагмент керна',
                'verbose_name_plural': 'Фрагменты керна',
            },
        ),
    ]
