# Generated by Django 2.2.6 on 2019-10-13 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_sample', '0004_auto_20191013_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='core_sample',
            name='name',
            field=models.CharField(default='some', max_length=50, verbose_name='Название'),
            preserve_default=False,
        ),
    ]
