# Generated by Django 2.2.6 on 2019-10-13 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_sample', '0005_core_sample_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='core_sample',
            name='status',
            field=models.CharField(choices=[(1, 'notAnalysed'), (2, 'analysed'), (3, 'inProcess'), (4, 'error')], default=1, max_length=32, verbose_name='Статус'),
        ),
    ]
