# Generated by Django 2.2.6 on 2019-10-13 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_sample', '0007_auto_20191013_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='core_sample',
            name='status',
            field=models.IntegerField(choices=[(1, 'notAnalysed'), (2, 'analysed'), (3, 'inProcess'), (4, 'error')], default=1, verbose_name='Статус'),
        ),
    ]
