# Generated by Django 2.2.6 on 2019-10-25 09:44

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core_sample', '0010_auto_20191025_1223'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Oil_layer_model',
            new_name='Carbon_layer_m',
        ),
        migrations.RenameModel(
            old_name='Core_sample_model',
            new_name='Core_sample_m',
        ),
        migrations.RenameModel(
            old_name='Disruption_layer_model',
            new_name='Disruption_layer_m',
        ),
        migrations.RenameModel(
            old_name='Fragment_model',
            new_name='Fragment_m',
        ),
        migrations.RenameModel(
            old_name='Carbon_layer_model',
            new_name='Oil_layer_m',
        ),
        migrations.RenameModel(
            old_name='Rock_layer_model',
            new_name='Rock_layer_m',
        ),
        migrations.AlterModelOptions(
            name='carbon_layer_m',
            options={'verbose_name': 'Слой карбонатности', 'verbose_name_plural': 'Слои карбонатности'},
        ),
        migrations.AlterModelOptions(
            name='oil_layer_m',
            options={'verbose_name': 'Слой нефтенасыщенности', 'verbose_name_plural': 'Слои нефтенасыщенности'},
        ),
    ]
