# Generated by Django 2.2.6 on 2019-10-13 23:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    atomic = False

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Core_sample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('global_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('deposit', models.PositiveIntegerField(verbose_name='Месторождение')),
                ('hole', models.PositiveIntegerField(verbose_name='Скважина')),
                ('top', models.FloatField(verbose_name='Вверх')),
                ('bottom', models.FloatField(verbose_name='Низ')),
                ('status', models.IntegerField(choices=[(1, 'notAnalysed'), (2, 'analysed'), (3, 'inProcess'), (4, 'error')], default=1, verbose_name='Статус')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Керн',
                'verbose_name_plural': 'Керны',
            },
        ),
        migrations.CreateModel(
            name='Fragment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dl_src', models.FilePathField(verbose_name='ДС изображение')),
                ('uv_src', models.FilePathField(verbose_name='УФ изображение')),
                ('top', models.FloatField(verbose_name='Вверх')),
                ('bottom', models.FloatField(verbose_name='Низ')),
                ('cs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_sample.Core_sample', verbose_name='Керн')),
            ],
            options={
                'verbose_name': 'Фрагмент керна',
                'verbose_name_plural': 'Фрагменты керна',
            },
        ),
    ]
