# Generated by Django 2.2.6 on 2019-10-14 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_sample', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='core_sample',
            name='control_sum',
            field=models.CharField(default='temp sum', max_length=100, verbose_name='Контрольная сумма'),
            preserve_default=False,
        ),
    ]
