# Generated by Django 2.2.6 on 2019-10-22 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_sample', '0003_core_sample_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='fragment',
            name='density',
            field=models.FloatField(default=100.0, verbose_name='Плотность'),
            preserve_default=False,
        ),
    ]
