# Generated by Django 2.2.6 on 2019-10-22 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_sample', '0007_remove_markup_version'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rock_layer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top', models.FloatField(verbose_name='Вверх')),
                ('bottom', models.FloatField(verbose_name='Низ')),
                ('class_label', models.IntegerField(choices=[(1, 'siltstone'), (2, 'sandstone'), (3, 'clay')], verbose_name='Класс')),
                ('markup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_sample.Markup', verbose_name='Разметка')),
            ],
            options={
                'verbose_name': 'Слой породы',
                'verbose_name_plural': 'Слои породы',
            },
        ),
        migrations.CreateModel(
            name='Oil_layer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top', models.FloatField(verbose_name='Вверх')),
                ('bottom', models.FloatField(verbose_name='Низ')),
                ('class_label', models.IntegerField(choices=[(1, 'notDefined'), (2, 'low'), (3, 'high')], verbose_name='Класс')),
                ('markup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_sample.Markup', verbose_name='Разметка')),
            ],
            options={
                'verbose_name': 'Слой нефтенасыщенности',
                'verbose_name_plural': 'Слои нефтенасыщенности',
            },
        ),
        migrations.CreateModel(
            name='Disruption_layer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top', models.FloatField(verbose_name='Вверх')),
                ('bottom', models.FloatField(verbose_name='Низ')),
                ('class_label', models.IntegerField(choices=[(1, 'none'), (2, 'low'), (3, 'high')], verbose_name='Класс')),
                ('markup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_sample.Markup', verbose_name='Разметка')),
            ],
            options={
                'verbose_name': 'Слой разрушенности',
                'verbose_name_plural': 'Слои разрушенности',
            },
        ),
        migrations.CreateModel(
            name='Carbon_layer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top', models.FloatField(verbose_name='Вверх')),
                ('bottom', models.FloatField(verbose_name='Низ')),
                ('class_label', models.IntegerField(choices=[(1, 'notDefined'), (2, 'low'), (3, 'high')], verbose_name='Класс')),
                ('markup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_sample.Markup', verbose_name='Разметка')),
            ],
            options={
                'verbose_name': 'Слой карбонатности',
                'verbose_name_plural': 'Слои карбонатности',
            },
        ),
    ]
