# Generated by Django 2.2.6 on 2019-10-25 09:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core_sample', '0008_carbon_layer_disruption_layer_oil_layer_rock_layer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rock_layer_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top', models.FloatField(verbose_name='Вверх')),
                ('bottom', models.FloatField(verbose_name='Низ')),
                ('class_label', models.IntegerField(choices=[(1, 'siltstone'), (2, 'sandstone'), (3, 'mudstone')], verbose_name='Класс')),
            ],
            options={
                'verbose_name': 'Слой породы',
                'verbose_name_plural': 'Слои породы',
            },
        ),
        migrations.RenameModel(
            old_name='Carbon_layer',
            new_name='Carbon_layer_model',
        ),
        migrations.RenameModel(
            old_name='Core_sample',
            new_name='Core_sample_model',
        ),
        migrations.RenameModel(
            old_name='Disruption_layer',
            new_name='Disruption_layer_model',
        ),
        migrations.RenameModel(
            old_name='Fragment',
            new_name='Fragment_model',
        ),
        migrations.RenameModel(
            old_name='Oil_layer',
            new_name='Oil_layer_model',
        ),
        migrations.RenameModel(
            old_name='Markup',
            new_name='Markup_model',
        ),
        migrations.DeleteModel(
            name='Rock_layer',
        ),
        migrations.AddField(
            model_name='rock_layer_model',
            name='markup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_sample.Markup_model', verbose_name='Разметка'),
        ),
    ]
