# Generated by Django 2.2.6 on 2019-10-25 09:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

	atomic = False


    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core_sample', '0009_auto_20191025_1209'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Markup_model',
            new_name='Markup_m',
        ),
    ]
