# Generated by Django 2.2.6 on 2019-10-25 10:03

from django.db import migrations


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('core_sample', '0011_auto_20191025_1244'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Disruption_layer_m',
            new_name='Ruin_layer_m',
        ),
    ]
