# Generated by Django 2.2.6 on 2019-10-25 10:25

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

	atomic = False

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core_sample', '0012_auto_20191025_1303'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Carbon_layer_m',
            new_name='Carbon_layer',
        ),
        migrations.RenameModel(
            old_name='Core_sample_m',
            new_name='Core_sample',
        ),
        migrations.RenameModel(
            old_name='Fragment_m',
            new_name='Fragment',
        ),
        migrations.RenameModel(
            old_name='Markup_m',
            new_name='Markup',
        ),
        migrations.RenameModel(
            old_name='Oil_layer_m',
            new_name='Oil_layer',
        ),
        migrations.RenameModel(
            old_name='Rock_layer_m',
            new_name='Rock_layer',
        ),
        migrations.RenameModel(
            old_name='Ruin_layer_m',
            new_name='Ruin_layer',
        ),
    ]
