# Generated by Django 2.2.6 on 2019-10-25 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_sample', '0014_auto_20191025_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='fragment',
            name='dl_height',
            field=models.IntegerField(default=0, verbose_name='Высота ДС (px)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fragment',
            name='dl_width',
            field=models.IntegerField(default=0, verbose_name='Ширина ДС (px)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fragment',
            name='uv_height',
            field=models.IntegerField(default=0, verbose_name='Высота УФ (px)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fragment',
            name='uv_width',
            field=models.IntegerField(default=0, verbose_name='Ширина УФ (px)'),
            preserve_default=False,
        ),
    ]
