# Generated by Django 2.2.6 on 2019-10-25 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_sample', '0015_auto_20191025_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carbon_layer',
            name='bottom',
            field=models.PositiveIntegerField(verbose_name='Низ'),
        ),
        migrations.AlterField(
            model_name='carbon_layer',
            name='top',
            field=models.PositiveIntegerField(verbose_name='Вверх'),
        ),
        migrations.AlterField(
            model_name='core_sample',
            name='bottom',
            field=models.PositiveIntegerField(verbose_name='Низ'),
        ),
        migrations.AlterField(
            model_name='core_sample',
            name='top',
            field=models.PositiveIntegerField(verbose_name='Вверх'),
        ),
        migrations.AlterField(
            model_name='fragment',
            name='bottom',
            field=models.PositiveIntegerField(verbose_name='Низ'),
        ),
        migrations.AlterField(
            model_name='fragment',
            name='dl_height',
            field=models.PositiveIntegerField(verbose_name='Высота ДС (px)'),
        ),
        migrations.AlterField(
            model_name='fragment',
            name='dl_width',
            field=models.PositiveIntegerField(verbose_name='Ширина ДС (px)'),
        ),
        migrations.AlterField(
            model_name='fragment',
            name='top',
            field=models.PositiveIntegerField(verbose_name='Вверх'),
        ),
        migrations.AlterField(
            model_name='fragment',
            name='uv_height',
            field=models.PositiveIntegerField(verbose_name='Высота УФ (px)'),
        ),
        migrations.AlterField(
            model_name='fragment',
            name='uv_width',
            field=models.PositiveIntegerField(verbose_name='Ширина УФ (px)'),
        ),
        migrations.AlterField(
            model_name='oil_layer',
            name='bottom',
            field=models.PositiveIntegerField(verbose_name='Низ'),
        ),
        migrations.AlterField(
            model_name='oil_layer',
            name='top',
            field=models.PositiveIntegerField(verbose_name='Вверх'),
        ),
        migrations.AlterField(
            model_name='rock_layer',
            name='bottom',
            field=models.PositiveIntegerField(verbose_name='Низ'),
        ),
        migrations.AlterField(
            model_name='rock_layer',
            name='top',
            field=models.PositiveIntegerField(verbose_name='Вверх'),
        ),
        migrations.AlterField(
            model_name='ruin_layer',
            name='bottom',
            field=models.PositiveIntegerField(verbose_name='Низ'),
        ),
        migrations.AlterField(
            model_name='ruin_layer',
            name='top',
            field=models.PositiveIntegerField(verbose_name='Вверх'),
        ),
    ]
