# Generated by Django 2.2.6 on 2019-10-25 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_sample', '0016_auto_20191025_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carbon_layer',
            name='bottom',
            field=models.PositiveIntegerField(verbose_name='Низ (см)'),
        ),
        migrations.AlterField(
            model_name='carbon_layer',
            name='top',
            field=models.PositiveIntegerField(verbose_name='Вверх (см)'),
        ),
        migrations.AlterField(
            model_name='core_sample',
            name='bottom',
            field=models.PositiveIntegerField(verbose_name='Низ (см)'),
        ),
        migrations.AlterField(
            model_name='core_sample',
            name='top',
            field=models.PositiveIntegerField(verbose_name='Вверх (см)'),
        ),
        migrations.AlterField(
            model_name='fragment',
            name='bottom',
            field=models.PositiveIntegerField(verbose_name='Низ (см)'),
        ),
        migrations.AlterField(
            model_name='fragment',
            name='top',
            field=models.PositiveIntegerField(verbose_name='Вверх (см)'),
        ),
        migrations.AlterField(
            model_name='oil_layer',
            name='bottom',
            field=models.PositiveIntegerField(verbose_name='Низ (см)'),
        ),
        migrations.AlterField(
            model_name='oil_layer',
            name='top',
            field=models.PositiveIntegerField(verbose_name='Вверх (см)'),
        ),
        migrations.AlterField(
            model_name='rock_layer',
            name='bottom',
            field=models.PositiveIntegerField(verbose_name='Низ (см)'),
        ),
        migrations.AlterField(
            model_name='rock_layer',
            name='top',
            field=models.PositiveIntegerField(verbose_name='Вверх (см)'),
        ),
        migrations.AlterField(
            model_name='ruin_layer',
            name='bottom',
            field=models.PositiveIntegerField(verbose_name='Низ (см)'),
        ),
        migrations.AlterField(
            model_name='ruin_layer',
            name='top',
            field=models.PositiveIntegerField(verbose_name='Вверх (см)'),
        ),
    ]
