# Generated by Django 2.2.6 on 2019-11-28 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_sample', '0017_auto_20191025_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rock_layer',
            name='class_label',
            field=models.IntegerField(choices=[(1, 'siltstone'), (2, 'sandstone'), (3, 'mudstone'), (4, 'other')], verbose_name='Класс'),
        ),
    ]
