language: python

branches:
  only:
  - project/feature/CI&CD

# Версии python для которых нужно производить сборки
python:
  - "3.7"

# Установка зависимостей в окружение
install:
  - pip install -r mainService/requirements.txt

# Запуск тестов
script: python mainService/manage.py test