language: python

branches:
  only:
  - project/feature/CI&CD

# Версии python для которых нужно производить сборки
python:
  - "3.7"


# Параметры окружения
env:
  - DJANGO_VERSION=2.2.6

# Установка зависимостей в окружение
install:
  - pip install -q Django==$DJANGO_VERSION
  - sh install.sh

# Запуск тестов
script: sh test.sh

# Билд и деплой
after_success: 
  - sh build.sh
  - sh deploy.sh
