# Generated by Django 2.2.5 on 2019-09-21 14:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workstation', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workstation',
            options={'verbose_name': 'Рабочие окружение', 'verbose_name_plural': 'Рабочие окружения'},
        ),
        migrations.AddField(
            model_name='workstation',
            name='creator',
            field=models.ForeignKey(default=None, editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Создатель'),
        ),
        migrations.AddField(
            model_name='workstation',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания'),
        ),
        migrations.AddField(
            model_name='workstation',
            name='description',
            field=models.TextField(max_length=200, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='workstation',
            name='invited',
            field=models.ManyToManyField(related_name='invited_worker', to=settings.AUTH_USER_MODEL, verbose_name='Участники'),
        ),
        migrations.AddField(
            model_name='workstation',
            name='title',
            field=models.CharField(max_length=50, null=True, verbose_name='Название'),
        ),
    ]
