# Generated by Django 2.2.5 on 2019-09-21 15:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workstation', '0002_auto_20190921_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workstation',
            name='creator',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Создатель'),
        ),
    ]
